configfile: "config/config.yaml"

envvars:
    "ODD_DIR",

rule simulated_particles:
    output:
        "tmp/tracksummary_gsf.root",
        "tmp/tracksummary_kf.root",
    script:
        "scripts/simulation.py"

rule compute_zmasses:
    output:
        "tmp/masses_gsf.csv",
        "tmp/masses_kf.csv",
    input:
        "tmp/tracksummary_gsf.root",
        "tmp/tracksummary_kf.root",
    script:
        "scripts/compute_zmass.py"

rule fit_masses_scipy:
    input:
        "tmp/masses_gsf.csv",
        "tmp/masses_kf.csv",
    output:
        "plots/z0_mass_fit_scipy.png"
    script:
        "scripts/fit_zmass_scipy.py"


rule fit_masses_root:
    input:
        "tmp/masses_gsf.csv",
        "tmp/masses_kf.csv",
    output:
        "plots/z0_mass_fit_root.png"
    script:
        "scripts/fit_zmass_root.py"


rule all:
    default_target: True
    input:
        "plots/z0_mass_fit_scipy.png",
        "plots/z0_mass_fit_root.png"
